baseURL = "https://pastriesbygrey.jasik.xyz"
languageCode = "en-us"
title = "Pastries By Grey"

menu_group = "pastry"

[params]
description = "Pastries By Grey is run by Noah Jasik - I am a home baker and currently an Advanced Culinary student at Cy-Fair and I enjoy pastry arts. I am from and live in Cypress, TX and I am a Award-winning baker for my cupcakes."

[taxonomies]
menu_group = "menu_group"