baseURL = "https://pastriesbygrey.jasik.xyz"
languageCode = "en-us"
title = "Pastries By Grey"

menu_group = "pastry"

[params]
description = "Pastries By Grey is run by Noah Jasik - I am a home baker and currently a Texas A&M student.  I am a Award-winning baker for my cupcakes."

[taxonomies]
menu_group = "menu_group"
